/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings/route'
import { Route as LogsRouteImport } from './routes/logs/route'
import { Route as CreationsRouteImport } from './routes/creations/route'
import { Route as ContactMeRouteImport } from './routes/contact-me/route'
import { Route as BioRouteImport } from './routes/bio/route'
import { Route as AchievementsRouteImport } from './routes/achievements/route'
import { Route as AboutMeRouteImport } from './routes/about-me/route'
import { Route as IndexImport } from './routes/index'
import { Route as LogsIndexImport } from './routes/logs/index'
import { Route as CreationsIndexImport } from './routes/creations/index'
import { Route as ContactMeIndexImport } from './routes/contact-me/index'
import { Route as BioIndexImport } from './routes/bio/index'
import { Route as AchievementsIndexImport } from './routes/achievements/index'
import { Route as CreationsSlugIndexImport } from './routes/creations/$slug/index'
import { Route as AchievementsSlugIndexImport } from './routes/achievements/$slug/index'

// Create/Update Routes

const SettingsRouteRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const LogsRouteRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRoute,
} as any)

const CreationsRouteRoute = CreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => rootRoute,
} as any)

const ContactMeRouteRoute = ContactMeRouteImport.update({
  id: '/contact-me',
  path: '/contact-me',
  getParentRoute: () => rootRoute,
} as any)

const BioRouteRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRoute,
} as any)

const AchievementsRouteRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRoute,
} as any)

const AboutMeRouteRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LogsIndexRoute = LogsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogsRouteRoute,
} as any)

const CreationsIndexRoute = CreationsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreationsRouteRoute,
} as any)

const ContactMeIndexRoute = ContactMeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactMeRouteRoute,
} as any)

const BioIndexRoute = BioIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BioRouteRoute,
} as any)

const AchievementsIndexRoute = AchievementsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AchievementsRouteRoute,
} as any)

const CreationsSlugIndexRoute = CreationsSlugIndexImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => CreationsRouteRoute,
} as any)

const AchievementsSlugIndexRoute = AchievementsSlugIndexImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => AchievementsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRoute
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRoute
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRoute
    }
    '/contact-me': {
      id: '/contact-me'
      path: '/contact-me'
      fullPath: '/contact-me'
      preLoaderRoute: typeof ContactMeRouteImport
      parentRoute: typeof rootRoute
    }
    '/creations': {
      id: '/creations'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof CreationsRouteImport
      parentRoute: typeof rootRoute
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/achievements/': {
      id: '/achievements/'
      path: '/'
      fullPath: '/achievements/'
      preLoaderRoute: typeof AchievementsIndexImport
      parentRoute: typeof AchievementsRouteImport
    }
    '/bio/': {
      id: '/bio/'
      path: '/'
      fullPath: '/bio/'
      preLoaderRoute: typeof BioIndexImport
      parentRoute: typeof BioRouteImport
    }
    '/contact-me/': {
      id: '/contact-me/'
      path: '/'
      fullPath: '/contact-me/'
      preLoaderRoute: typeof ContactMeIndexImport
      parentRoute: typeof ContactMeRouteImport
    }
    '/creations/': {
      id: '/creations/'
      path: '/'
      fullPath: '/creations/'
      preLoaderRoute: typeof CreationsIndexImport
      parentRoute: typeof CreationsRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexImport
      parentRoute: typeof LogsRouteImport
    }
    '/achievements/$slug/': {
      id: '/achievements/$slug/'
      path: '/$slug'
      fullPath: '/achievements/$slug'
      preLoaderRoute: typeof AchievementsSlugIndexImport
      parentRoute: typeof AchievementsRouteImport
    }
    '/creations/$slug/': {
      id: '/creations/$slug/'
      path: '/$slug'
      fullPath: '/creations/$slug'
      preLoaderRoute: typeof CreationsSlugIndexImport
      parentRoute: typeof CreationsRouteImport
    }
  }
}

// Create and export the route tree

interface AchievementsRouteRouteChildren {
  AchievementsIndexRoute: typeof AchievementsIndexRoute
  AchievementsSlugIndexRoute: typeof AchievementsSlugIndexRoute
}

const AchievementsRouteRouteChildren: AchievementsRouteRouteChildren = {
  AchievementsIndexRoute: AchievementsIndexRoute,
  AchievementsSlugIndexRoute: AchievementsSlugIndexRoute,
}

const AchievementsRouteRouteWithChildren =
  AchievementsRouteRoute._addFileChildren(AchievementsRouteRouteChildren)

interface BioRouteRouteChildren {
  BioIndexRoute: typeof BioIndexRoute
}

const BioRouteRouteChildren: BioRouteRouteChildren = {
  BioIndexRoute: BioIndexRoute,
}

const BioRouteRouteWithChildren = BioRouteRoute._addFileChildren(
  BioRouteRouteChildren,
)

interface ContactMeRouteRouteChildren {
  ContactMeIndexRoute: typeof ContactMeIndexRoute
}

const ContactMeRouteRouteChildren: ContactMeRouteRouteChildren = {
  ContactMeIndexRoute: ContactMeIndexRoute,
}

const ContactMeRouteRouteWithChildren = ContactMeRouteRoute._addFileChildren(
  ContactMeRouteRouteChildren,
)

interface CreationsRouteRouteChildren {
  CreationsIndexRoute: typeof CreationsIndexRoute
  CreationsSlugIndexRoute: typeof CreationsSlugIndexRoute
}

const CreationsRouteRouteChildren: CreationsRouteRouteChildren = {
  CreationsIndexRoute: CreationsIndexRoute,
  CreationsSlugIndexRoute: CreationsSlugIndexRoute,
}

const CreationsRouteRouteWithChildren = CreationsRouteRoute._addFileChildren(
  CreationsRouteRouteChildren,
)

interface LogsRouteRouteChildren {
  LogsIndexRoute: typeof LogsIndexRoute
}

const LogsRouteRouteChildren: LogsRouteRouteChildren = {
  LogsIndexRoute: LogsIndexRoute,
}

const LogsRouteRouteWithChildren = LogsRouteRoute._addFileChildren(
  LogsRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRouteRoute
  '/achievements': typeof AchievementsRouteRouteWithChildren
  '/bio': typeof BioRouteRouteWithChildren
  '/contact-me': typeof ContactMeRouteRouteWithChildren
  '/creations': typeof CreationsRouteRouteWithChildren
  '/logs': typeof LogsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/bio/': typeof BioIndexRoute
  '/contact-me/': typeof ContactMeIndexRoute
  '/creations/': typeof CreationsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/achievements/$slug': typeof AchievementsSlugIndexRoute
  '/creations/$slug': typeof CreationsSlugIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/achievements': typeof AchievementsIndexRoute
  '/bio': typeof BioIndexRoute
  '/contact-me': typeof ContactMeIndexRoute
  '/creations': typeof CreationsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/achievements/$slug': typeof AchievementsSlugIndexRoute
  '/creations/$slug': typeof CreationsSlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRouteRoute
  '/achievements': typeof AchievementsRouteRouteWithChildren
  '/bio': typeof BioRouteRouteWithChildren
  '/contact-me': typeof ContactMeRouteRouteWithChildren
  '/creations': typeof CreationsRouteRouteWithChildren
  '/logs': typeof LogsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/bio/': typeof BioIndexRoute
  '/contact-me/': typeof ContactMeIndexRoute
  '/creations/': typeof CreationsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/achievements/$slug/': typeof AchievementsSlugIndexRoute
  '/creations/$slug/': typeof CreationsSlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/achievements'
    | '/bio'
    | '/contact-me'
    | '/creations'
    | '/logs'
    | '/settings'
    | '/achievements/'
    | '/bio/'
    | '/contact-me/'
    | '/creations/'
    | '/logs/'
    | '/achievements/$slug'
    | '/creations/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-me'
    | '/settings'
    | '/achievements'
    | '/bio'
    | '/contact-me'
    | '/creations'
    | '/logs'
    | '/achievements/$slug'
    | '/creations/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-me'
    | '/achievements'
    | '/bio'
    | '/contact-me'
    | '/creations'
    | '/logs'
    | '/settings'
    | '/achievements/'
    | '/bio/'
    | '/contact-me/'
    | '/creations/'
    | '/logs/'
    | '/achievements/$slug/'
    | '/creations/$slug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRouteRoute: typeof AboutMeRouteRoute
  AchievementsRouteRoute: typeof AchievementsRouteRouteWithChildren
  BioRouteRoute: typeof BioRouteRouteWithChildren
  ContactMeRouteRoute: typeof ContactMeRouteRouteWithChildren
  CreationsRouteRoute: typeof CreationsRouteRouteWithChildren
  LogsRouteRoute: typeof LogsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRouteRoute: AboutMeRouteRoute,
  AchievementsRouteRoute: AchievementsRouteRouteWithChildren,
  BioRouteRoute: BioRouteRouteWithChildren,
  ContactMeRouteRoute: ContactMeRouteRouteWithChildren,
  CreationsRouteRoute: CreationsRouteRouteWithChildren,
  LogsRouteRoute: LogsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about-me",
        "/achievements",
        "/bio",
        "/contact-me",
        "/creations",
        "/logs",
        "/settings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about-me": {
      "filePath": "about-me/route.tsx"
    },
    "/achievements": {
      "filePath": "achievements/route.tsx",
      "children": [
        "/achievements/",
        "/achievements/$slug/"
      ]
    },
    "/bio": {
      "filePath": "bio/route.tsx",
      "children": [
        "/bio/"
      ]
    },
    "/contact-me": {
      "filePath": "contact-me/route.tsx",
      "children": [
        "/contact-me/"
      ]
    },
    "/creations": {
      "filePath": "creations/route.tsx",
      "children": [
        "/creations/",
        "/creations/$slug/"
      ]
    },
    "/logs": {
      "filePath": "logs/route.tsx",
      "children": [
        "/logs/"
      ]
    },
    "/settings": {
      "filePath": "settings/route.tsx"
    },
    "/achievements/": {
      "filePath": "achievements/index.tsx",
      "parent": "/achievements"
    },
    "/bio/": {
      "filePath": "bio/index.tsx",
      "parent": "/bio"
    },
    "/contact-me/": {
      "filePath": "contact-me/index.tsx",
      "parent": "/contact-me"
    },
    "/creations/": {
      "filePath": "creations/index.tsx",
      "parent": "/creations"
    },
    "/logs/": {
      "filePath": "logs/index.tsx",
      "parent": "/logs"
    },
    "/achievements/$slug/": {
      "filePath": "achievements/$slug/index.tsx",
      "parent": "/achievements"
    },
    "/creations/$slug/": {
      "filePath": "creations/$slug/index.tsx",
      "parent": "/creations"
    }
  }
}
ROUTE_MANIFEST_END */
